/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDCONTROLLER_AUTODEFS_H
#define S3EANDROIDCONTROLLER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDCONTROLLER_NAME "s3eAndroidController"
#define S3E_EXT_ANDROIDCONTROLLER_HASH 0xb381b915

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eAndroidController", 13)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EANDROIDCONTROLLER_AUTODEFS_H */
