/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EFIRETV_AUTODEFS_H
#define S3EFIRETV_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FIRETV_NAME "s3eFireTV"
#define S3E_EXT_FIRETV_HASH 0xab752c60

#endif /* !S3EFIRETV_AUTODEFS_H */
