/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eAndroidControllerRegister_t)(s3eAndroidControllerCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eAndroidControllerUnRegister_t)(s3eAndroidControllerCallback cbid, s3eCallback fn);
typedef       void(*s3eAndroidControllerStartFrame_t)();
typedef       bool(*s3eAndroidControllerSelectControllerByPlayer_t)(int player);
typedef        int(*s3eAndroidControllerGetPlayerCount_t)();
typedef       bool(*s3eAndroidControllerGetButtonState_t)(int button);
typedef      float(*s3eAndroidControllerGetAxisValue_t)(int axis);
typedef  s3eResult(*s3eAndroidControllerGetButtonDisplayName_t)(char* dst, int button, s3eBool terminateString);
typedef  s3eResult(*s3eAndroidControllerGetAxisDisplayName_t)(char* dst, int axis, s3eBool terminateString);
typedef       void(*s3eAndroidControllerSetPropagateButtonsToKeyboard_t)(bool propagate);
typedef       bool(*s3eAndroidControllerGetPropagateButtonsToKeyboard_t)();
typedef       bool(*s3eAndroidControllerIsTypeSupported_t)(s3eAndroidControllerType type);
typedef  s3eResult(*s3eAndroidControllerSetType_t)(s3eAndroidControllerType type);
typedef s3eAndroidControllerType(*s3eAndroidControllerGetType_t)();

/**
 * struct that gets filled in by s3eAndroidControllerRegister
 */
typedef struct s3eAndroidControllerFuncs
{
    s3eAndroidControllerRegister_t m_s3eAndroidControllerRegister;
    s3eAndroidControllerUnRegister_t m_s3eAndroidControllerUnRegister;
    s3eAndroidControllerStartFrame_t m_s3eAndroidControllerStartFrame;
    s3eAndroidControllerSelectControllerByPlayer_t m_s3eAndroidControllerSelectControllerByPlayer;
    s3eAndroidControllerGetPlayerCount_t m_s3eAndroidControllerGetPlayerCount;
    s3eAndroidControllerGetButtonState_t m_s3eAndroidControllerGetButtonState;
    s3eAndroidControllerGetAxisValue_t m_s3eAndroidControllerGetAxisValue;
    s3eAndroidControllerGetButtonDisplayName_t m_s3eAndroidControllerGetButtonDisplayName;
    s3eAndroidControllerGetAxisDisplayName_t m_s3eAndroidControllerGetAxisDisplayName;
    s3eAndroidControllerSetPropagateButtonsToKeyboard_t m_s3eAndroidControllerSetPropagateButtonsToKeyboard;
    s3eAndroidControllerGetPropagateButtonsToKeyboard_t m_s3eAndroidControllerGetPropagateButtonsToKeyboard;
    s3eAndroidControllerIsTypeSupported_t m_s3eAndroidControllerIsTypeSupported;
    s3eAndroidControllerSetType_t m_s3eAndroidControllerSetType;
    s3eAndroidControllerGetType_t m_s3eAndroidControllerGetType;
} s3eAndroidControllerFuncs;
