/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eFireTV.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eFireTV_startFrame_t)();
typedef       bool(*s3eFireTV_selectControllerByPlayer_t)(int player);
typedef        int(*s3eFireTV_getPlayerCount_t)();
typedef       bool(*s3eFireTV_getButtonState_t)(int button);
typedef      float(*s3eFireTV_getAxisValue_t)(int axis);

/**
 * struct that gets filled in by s3eFireTVRegister
 */
typedef struct s3eFireTVFuncs
{
    s3eFireTV_startFrame_t m_s3eFireTV_startFrame;
    s3eFireTV_selectControllerByPlayer_t m_s3eFireTV_selectControllerByPlayer;
    s3eFireTV_getPlayerCount_t m_s3eFireTV_getPlayerCount;
    s3eFireTV_getButtonState_t m_s3eFireTV_getButtonState;
    s3eFireTV_getAxisValue_t m_s3eFireTV_getAxisValue;
} s3eFireTVFuncs;

static s3eFireTVFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xab752c60, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eFireTV");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xab752c60, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eFireTVAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eFireTV_startFrame()
{
    IwTrace(FIRETV_VERBOSE, ("calling s3eFireTV[0] func: s3eFireTV_startFrame"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eFireTV_startFrame();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}

bool s3eFireTV_selectControllerByPlayer(int player)
{
    IwTrace(FIRETV_VERBOSE, ("calling s3eFireTV[1] func: s3eFireTV_selectControllerByPlayer"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eFireTV_selectControllerByPlayer(player);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

int s3eFireTV_getPlayerCount()
{
    IwTrace(FIRETV_VERBOSE, ("calling s3eFireTV[2] func: s3eFireTV_getPlayerCount"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    int ret = g_Ext.m_s3eFireTV_getPlayerCount();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool s3eFireTV_getButtonState(int button)
{
    IwTrace(FIRETV_VERBOSE, ("calling s3eFireTV[3] func: s3eFireTV_getButtonState"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eFireTV_getButtonState(button);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

float s3eFireTV_getAxisValue(int axis)
{
    IwTrace(FIRETV_VERBOSE, ("calling s3eFireTV[4] func: s3eFireTV_getAxisValue"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    float ret = g_Ext.m_s3eFireTV_getAxisValue(axis);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}
