/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eAndroidController_autodefs.h"
#include "s3eEdk.h"
#include "s3eAndroidController.h"
//Declarations of Init and Term functions
extern s3eResult s3eAndroidControllerInit();
extern void s3eAndroidControllerTerminate();


void s3eAndroidControllerRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[8];
    funcPtrs[0] = (void*)s3eAndroidControllerStartFrame;
    funcPtrs[1] = (void*)s3eAndroidControllerSelectControllerByPlayer;
    funcPtrs[2] = (void*)s3eAndroidControllerGetPlayerCount;
    funcPtrs[3] = (void*)s3eAndroidControllerGetButtonState;
    funcPtrs[4] = (void*)s3eAndroidControllerGetAxisValue;
    funcPtrs[5] = (void*)s3eAndroidControllerGetButtonDisplayName;
    funcPtrs[6] = (void*)s3eAndroidControllerGetAxisDisplayName;
    funcPtrs[7] = (void*)s3eAndroidControllerSetPropagateButtonsToKeyboard;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[8] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eAndroidController", funcPtrs, sizeof(funcPtrs), flags, s3eAndroidControllerInit, s3eAndroidControllerTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eAndroidControllerStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eAndroidControllerRegisterExt;
    return 0;
}

int g_s3eAndroidControllerVal = s3eAndroidControllerStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eAndroidControllerRegisterExt();
}
#endif

#endif
