/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_ANDROIDCONTROLLER_H
#define S3E_EXT_ANDROIDCONTROLLER_H

#include <s3eTypes.h>

#define S3E_ANDROID_CONTROLLER_MAX_PLAYERS               4

#define S3E_ANDROID_CONTROLLER_AXIS_COUNT                6
#define S3E_ANDROID_CONTROLLER_BUTTON_COUNT              15

#define S3E_ANDROID_CONTROLLER_AXIS_STICK_LEFT_X         0
#define S3E_ANDROID_CONTROLLER_AXIS_STICK_LEFT_Y         1
#define S3E_ANDROID_CONTROLLER_AXIS_STICK_RIGHT_X        11
#define S3E_ANDROID_CONTROLLER_AXIS_STICK_RIGHT_Y        14
#define S3E_ANDROID_CONTROLLER_AXIS_TRIGGER_LEFT         23
#define S3E_ANDROID_CONTROLLER_AXIS_TRIGGER_RIGHT        22
#define S3E_ANDROID_CONTROLLER_BUTTON_A                  96
#define S3E_ANDROID_CONTROLLER_BUTTON_B                  97
#define S3E_ANDROID_CONTROLLER_BUTTON_DPAD_CENTER        23
#define S3E_ANDROID_CONTROLLER_BUTTON_DPAD_DOWN          20
#define S3E_ANDROID_CONTROLLER_BUTTON_DPAD_LEFT          21
#define S3E_ANDROID_CONTROLLER_BUTTON_DPAD_RIGHT         22
#define S3E_ANDROID_CONTROLLER_BUTTON_DPAD_UP            19
#define S3E_ANDROID_CONTROLLER_BUTTON_SHOULDER_LEFT      102
#define S3E_ANDROID_CONTROLLER_BUTTON_SHOULDER_RIGHT     103
#define S3E_ANDROID_CONTROLLER_BUTTON_STICK_LEFT         106
#define S3E_ANDROID_CONTROLLER_BUTTON_STICK_RIGHT        107
#define S3E_ANDROID_CONTROLLER_BUTTON_TRIGGER_LEFT       104
#define S3E_ANDROID_CONTROLLER_BUTTON_TRIGGER_RIGHT      105
#define S3E_ANDROID_CONTROLLER_BUTTON_X                  99
#define S3E_ANDROID_CONTROLLER_BUTTON_Y                  100
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the AndroidController extension is available.
 */
s3eBool s3eAndroidControllerAvailable();

void s3eAndroidControllerStartFrame();

bool s3eAndroidControllerSelectControllerByPlayer(int player);

int s3eAndroidControllerGetPlayerCount();

bool s3eAndroidControllerGetButtonState(int button);

float s3eAndroidControllerGetAxisValue(int axis);

s3eResult s3eAndroidControllerGetButtonDisplayName(char* dst, int button, s3eBool terminateString S3E_DEFAULT(S3E_TRUE));

s3eResult s3eAndroidControllerGetAxisDisplayName(char* dst, int axis, s3eBool terminateString S3E_DEFAULT(S3E_TRUE));

void s3eAndroidControllerSetPropagateButtonsToKeyboard(bool propagate);

S3E_END_C_DECL

#endif /* !S3E_EXT_ANDROIDCONTROLLER_H */
