/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_FIRETV_H
#define S3E_EXT_FIRETV_H

#include <s3eTypes.h>

#define s3eFireTV_MAX_PLAYERS               4

#define s3eFireTV_AXIS_STICK_LEFT_X         0
#define s3eFireTV_AXIS_STICK_LEFT_Y         1
#define s3eFireTV_AXIS_STICK_RIGHT_X        11
#define s3eFireTV_AXIS_STICK_RIGHT_Y        14
#define s3eFireTV_AXIS_TRIGGER_LEFT         23
#define s3eFireTV_AXIS_TRIGGER_RIGHT        22
#define s3eFireTV_AXIS_DPAD_X               15
#define s3eFireTV_AXIS_DPAD_Y               16

#define s3eFireTV_BUTTON_A                  96
#define s3eFireTV_BUTTON_B                  97
#define s3eFireTV_BUTTON_SHOULDER_LEFT      102
#define s3eFireTV_BUTTON_SHOULDER_RIGHT     103
#define s3eFireTV_BUTTON_STICK_LEFT         106
#define s3eFireTV_BUTTON_STICK_RIGHT        107
#define s3eFireTV_BUTTON_TRIGGER_LEFT       104
#define s3eFireTV_BUTTON_TRIGGER_RIGHT      105
#define s3eFireTV_BUTTON_X                  99
#define s3eFireTV_BUTTON_Y                  100
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the FireTV extension is available.
 */
s3eBool s3eFireTVAvailable();

void s3eFireTV_startFrame();

bool s3eFireTV_selectControllerByPlayer(int player);

int s3eFireTV_getPlayerCount();

bool s3eFireTV_getButtonState(int button);

float s3eFireTV_getAxisValue(int axis);

S3E_END_C_DECL

#endif /* !S3E_EXT_FIRETV_H */
